[build-system]
requires = ["setuptools>=42", "wheel"]

[tool.black]
line-length = 120
target-version =  ['py37', 'py38', 'py39']
include = '''
^/(
    [^/]*.py
    | (benchmarks|build_scripts|chives|tests|tools)/.*\.pyi?
)$
'''
exclude = ''
